1.0.0 and 1.0.1 has been yanked
These releases have been yanked because they failed to compile with syn
1.0.84 and later.

```text
error[E0659]: `parse_quote_spanned` is ambiguous
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-1.0.0/src/pin_project/derive.rs:677:63
    |
677 |             proj_generics.make_where_clause().predicates.push(parse_quote_spanned! { span =>
    |                                                               ^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
note: `parse_quote_spanned` could refer to the macro defined here
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-1.0.0/src/utils.rs:22:1
    |
22  | / macro_rules! parse_quote_spanned {
23  | |     ($span:expr => $($tt:tt)*) => {
24  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
25  | |     };
26  | | }
    | |_^
note: `parse_quote_spanned` could also refer to the macro imported here
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-1.0.0/src/pin_project/derive.rs:3:32
    |
3   | use syn::{visit_mut::VisitMut, *};
    |                                ^
    = help: use `self::parse_quote_spanned` to refer to this macro unambiguously
```