Ignore clippy::missing_trait_methods lint in generated code
```
error: missing trait method provided by default: `pin_drop`
  --> tests/lint/../include/basic-safe-part.rs:71:30
   |
71 | #[::pin_project::pin_project(PinnedDrop)]
   |                              ^^^^^^^^^^
   |
   = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
   = note: `-D clippy::missing-trait-methods` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::missing_trait_methods)]`

error: missing trait method provided by default: `pin_drop`
  --> tests/lint/../include/basic-safe-part.rs:89:30
   |
89 | #[::pin_project::pin_project(PinnedDrop)]
   |                              ^^^^^^^^^^
   |
   = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods

error: missing trait method provided by default: `pin_drop`
   --> tests/lint/../include/basic-safe-part.rs:102:5
    |
102 |     PinnedDrop,
    |     ^^^^^^^^^^
    |
    = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods

error: missing trait method provided by default: `pin_drop`
   --> tests/lint/lib.rs:149:46
    |
149 |                 #[::pin_project::pin_project(PinnedDrop)]
    |                                              ^^^^^^^^^^
...
371 |         mac!();
    |         ------ in this macro invocation
    |
    = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
    = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)

error: missing trait method provided by default: `pin_drop`
   --> tests/lint/lib.rs:166:46
    |
166 |                 #[::pin_project::pin_project(PinnedDrop)]
    |                                              ^^^^^^^^^^
...
371 |         mac!();
    |         ------ in this macro invocation
    |
    = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
    = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)

error: missing trait method provided by default: `pin_drop`
   --> tests/lint/lib.rs:178:21
    |
178 |                     PinnedDrop,
    |                     ^^^^^^^^^^
...
371 |         mac!();
    |         ------ in this macro invocation
    |
    = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
    = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)

error: missing trait method provided by default: `pin_drop`
   --> tests/lint/lib.rs:453:46
    |
453 |                 #[::pin_project::pin_project(PinnedDrop)]
    |                                              ^^^^^^^^^^
...
658 |         mac!();
    |         ------ in this macro invocation
    |
    = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
    = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)

error: missing trait method provided by default: `pin_drop`
   --> tests/lint/lib.rs:470:46
    |
470 |                 #[::pin_project::pin_project(PinnedDrop)]
    |                                              ^^^^^^^^^^
...
658 |         mac!();
    |         ------ in this macro invocation
    |
    = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
    = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)

error: missing trait method provided by default: `pin_drop`
   --> tests/lint/lib.rs:482:21
    |
482 |                     PinnedDrop,
    |                     ^^^^^^^^^^
...
658 |         mac!();
    |         ------ in this macro invocation
    |
    = help: implement the missing `pin_drop` method of the `PinnedDrop` trait
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_trait_methods
    = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)
```