ci: Exclude no-core test on Miri
```
error: unsupported operation: `sched_getaffinity` is not supported on #![no_core] programs
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/thread/unix.rs:170:24
    |
170 |                     if libc::sched_getaffinity(0, size_of::<libc::cpu_set_t>(), &mut set) == 0 {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsupported operation occurred here
    |
    = help: this is likely not a bug in the program; it indicates that the program performed an operation that Miri does not support
    = note: stack backtrace:
            0: std::sys::thread::unix::available_parallelism
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/thread/unix.rs:170:24: 170:90
            1: std::thread::functions::available_parallelism
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/functions.rs:695:5: 695:33
            2: test::helpers::concurrency::get_concurrency
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/helpers/concurrency.rs:14:9: 14:40
            3: <fn() -> usize {test::helpers::concurrency::get_concurrency} as _core::ops::FnOnce<()>>::call_once - shim(fn() -> usize {test::helpers::concurrency::get_concurrency})
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5: 250:71
            4: test::console::get_formatter
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/console.rs:290:28: 290:77
            5: test::run_tests_console
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/console.rs:318:19: 318:52
            6: test::test_main_inner::<{closure@test::test_main_static::{closure#0}}>
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:170:19: 170:59
            7: test::test_main_static
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:195:5: 195:47
            8: main
                at no-location
```